/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:b3edb590-d7ae-429c-b8bd-771f562b1f11",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_GlqduzdXO",
    "aws_user_pools_web_client_id": "7b4dcaidjoc5s8am77est2vm8p",
    "oauth": {}
};


export default awsmobile;
