/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:0eca570d-3474-4132-ae24-09480145eb89",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_zIA1mniFS",
    "aws_user_pools_web_client_id": "s000miuia1g8behsn88pu59tr",
    "oauth": {}
};


export default awsmobile;
